#!/bin/bash

# Supabase Settings Table Setup Guide
# 이 스크립트는 가이드용입니다. Supabase Dashboard에서 수동으로 실행하세요.

echo "======================================"
echo "Supabase Settings Table 설정 가이드"
echo "======================================"
echo ""
echo "다음 단계를 따라주세요:"
echo ""
echo "1. Supabase Dashboard 접속"
echo "   https://app.supabase.com/project/YOUR_PROJECT_ID"
echo ""
echo "2. 왼쪽 메뉴에서 'SQL Editor' 클릭"
echo ""
echo "3. 'New Query' 버튼 클릭"
echo ""
echo "4. 다음 파일의 내용을 복사하여 붙여넣기:"
echo "   scripts/create-settings-table.sql"
echo ""
echo "5. 'Run' 버튼 클릭하여 SQL 실행"
echo ""
echo "6. 'Table Editor'에서 settings 테이블 확인"
echo ""
echo "======================================"
echo "완료 후 앱을 새로고침하세요!"
echo "======================================"
echo ""
echo "설정 방법:"
echo "- Admin으로 로그인"
echo "- 헤더 우측 설정 버튼(⚙️) 클릭"
echo "- '기능 활성화 설정'에서 각 기능 토글"
echo ""
echo "자세한 내용은 scripts/SETTINGS_SETUP.md 참조"
